### ISSUE TITLE
Dependency mismatch detected

### ISSUE THREAD

**Issue by kamir** [nirbar1985/country-compass-ai#1]
Following your bootstrap procedure using pyenv and poetry I run into this error:

2024-02-21 11:54:31.273 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/Users/mkaempf/GITHUB.2024/country-compass-ai/chatbot_ui.py", line 9, in <module>
    from agents.conversational_agent import create_agent
  File "/Users/mkaempf/GITHUB.2024/country-compass-ai/agents/conversational_agent.py", line 1, in <module>
    from langchain.agents import AgentExecutor
  File "/usr/local/lib/python3.11/site-packages/langchain/__init__.py", line 5, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import Agent, AgentExecutor
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 13, in <module>
    from langchain.agents.tools import InvalidTool
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/tools.py", line 5, in <module>
    from langchain.tools.base import BaseTool
  File "/usr/local/lib/python3.11/site-packages/langchain/tools/__init__.py", line 3, in <module>
    from langchain.tools.base import BaseTool
  File "/usr/local/lib/python3.11/site-packages/langchain/tools/base.py", line 8, in <module>
    from langchain.callbacks import get_callback_manager
  File "/usr/local/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 6, in <module>
    from langchain.callbacks.base import (
  File "/usr/local/lib/python3.11/site-packages/langchain/callbacks/base.py", line 7, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "/usr/local/lib/python3.11/site-packages/langchain/schema.py", line 133, in <module>
    class ChatGeneration(Generation):
  File "/usr/local/lib/python3.11/site-packages/langchain/schema.py", line 139, in ChatGeneration
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

Can you share insights on how to resolve that?

**Comment by kamir** [comment]
I managed to fix it.

First of all, I created an Annaconda environment. 
Then I defined all the versions explicitly in my **requirements.txt** file for pip.

pydantic>=1.0.0,<2.0.0
openai
streamlit
langchain
tiktoken
google-search-results
langchain-openai==0.0.5
python-dotenv>=1.0.1,<2.0.0
ipykernel>=6.29.0,<7.0.0  # This is a development dependency

Finally, the import should be this:

...

#from pydantic.v1 import BaseModel, Field, conlist
**from pydantic import BaseModel, Field, conlist**
